language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
script:
  - npm test
  - npm run build:docs
  - npm run build:lib
deploy:
  - provider: surge
    project: ./build/
    domain: ghg-react.surge.sh
    skip_cleanup: true
  - provider: npm
    email: stumblingrumblin@gmail.com
    api_key: 8064487a-9b91-43f8-ab14-c042c017c9e1

